### ISSUE TITLE
sketch code link is dead

### ISSUE THREAD

**Issue by MasterOrigamii** [antonymarion/inverseCSG#16]

**Comment by antonymarion** [comment]
Please use the web internet archive to get it locally.

Sketch code repo has been deleted by their maintainers

Please cf Installation like to sketch library is broken · Issue #8 · antonymarion/inverseCSG · GitHub https://github.com/antonymarion/inverseCSG/issues/8

**Comment by MasterOrigamii** [comment]
Thanks for the reply, not double checking the closed issues was my fault.
