### ISSUE TITLE
SketchNotResolvedException: null

### ISSUE THREAD

**Issue by Lancial** [antonymarion/inverseCSG#4]
Hi there,

I'm running on a virtual machine of Ubuntu 16.04. Build was successful as I followed along the instructions, but running examples won't terminate or will terminate with an error.

Here is the error when running on ex_011
[ex_011_0_0.log](https://github.com/antonymarion/inverseCSG/files/4454738/ex_011_0_0.log)

Traceback (most recent call last):
  File "main.py", line 46, in <module>
    sketch_pipeline.RunSketchPipeline()
  File "/home/lx1030/inverseCSG/sketch_pipeline.py", line 718, in RunSketchPipeline
    part_file[:-len('.data')])
  File "/home/lx1030/inverseCSG/point_cloud_seg.py", line 24, in SegmentPointCloud
    cluster_result.fit(points)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/cluster/_agglomerative.py", line 796, in fit
    X = check_array(X, ensure_min_samples=2, estimator=self)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py", line 586, in check_array
    context))
ValueError: Found array with 1 sample(s) (shape=(1, 3)) while a minimum of 2 is required by AgglomerativeClustering.

I will appreciate any help, thank you!

**Comment by antonymarion** [comment]
Hi,

You can run the example 11 with the following python script  https://github.com/antonymarion/inverseCSG/blob/master/run_tests.py

python3 run_tests.py ../build 011

If you still have some problems then you can compare your installation with the following CI on Travis: https://travis-ci.com/github/antonymarion/inverseCSG/builds/147114488

**Comment by Hippogriff** [comment]
@Lancial I am getting same clustering error. Did you find out the solution?

**Comment by antonymarion** [comment]
Hi all, 

To get any information about the algorithm, how to use it and the issue that you had using this code, you should contact the authors of this paper here: https://cdfg.mit.edu/publications/inversecsg-automatic-conversion-3d-models-csg-trees

For instance taodu at csail dot mit dot edu will give you some good advice.

Regards,
Antony
